# Generated by Django 4.2.11 on 2024-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_alter_note_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
