# Generated by Django 4.2.11 on 2024-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_alter_note_data_created_alter_note_data_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
